//LOGIN
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';

export const SET_PROFILE_USER = 'SET_PROFILE_USER';
export const USER_NO_EXIST = 'USER_NO_EXIST';
export const USER_AUTHORIZED = 'USER_AUTHORIZED';


export const START_FETCHING_ALL_NOTIFICATIONS = 'START_FETCHING_ALL_NOTIFICATIONS';
export const RECEIVED_NOTIFICATIONS = 'RECEIVED_NOTIFICATIONS';
export const ADD_NOTIFICATIONS = 'ADD_NOTIFICATIONS';
export const PUSH_NOTIFICATION = 'PUSH_NOTIFICATION';